name: Presubmit
on: [push, pull_request]

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["**/README.md"]'
          do_not_skip: '["pull_request"]'

  build-and-check:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Build and Check ${{ matrix.os }} ${{ matrix.compiler }}${{ matrix.threadsafe && ' ' || ' No Thread Safe' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        threadsafe: [true, false]
        compiler: [gcc, g++, clang]
        exclude:
          - os: macos-latest
            compiler: g++

    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update; sudo apt install -y ${{ matrix.compiler }} ruby-dev libgsl-dev python3-dev valgrind
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - run: brew install gsl automake libtool
        if: ${{ matrix.os == 'macos-latest' }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        if: ${{ matrix.os == 'macos-latest' }}
      - run: gem install --user-install rake ffi ffi-value whittle xmlrpc
      - run: pip3 install --user parglare
      - run: ./autogen.sh
      - run: mkdir -p build
      - run: ../configure --enable-strict${{ matrix.threadsafe && ' --enable-thread-safe' || ' --disable-thread-safe' }} CC=${{ matrix.compiler }}${{ (matrix.compiler == 'clang' && matrix.os == 'ubuntu-latest') && ' CFLAGS="-gdwarf-4 -O2"' || '' }}
        working-directory: build
      - run: make -j
        working-directory: build
      - run: make -j check
        working-directory: build
      - run: make -j check-valgrind-memcheck
        working-directory: build
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - run: make -j check-valgrind-helgrind
        working-directory: build
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: build-and-check
          path: |
            build/**/*.log
            build/config.log

  sanitizers:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Sanitizers ${{ matrix.sanitizer }}${{ matrix.threadsafe && ' ' || ' No Thread Safe' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [address, undefined]
        threadsafe: [true, false]

    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update; sudo apt install -y clang ruby-dev libgsl-dev python3-dev
      - run: gem install --user-install rake ffi ffi-value whittle xmlrpc
      - run: pip3 install --user parglare
      - run: ./autogen.sh
      - run: mkdir -p build
      - run: ../configure --enable-strict${{ matrix.threadsafe && ' --enable-thread-safe' || ' --disable-thread-safe' }} CC=clang CFLAGS="-gdwarf-4 -O2 -fsanitize=${{ matrix.sanitizer }} -fno-omit-frame-pointer" LDFLAGS="-fsanitize=${{ matrix.sanitizer }}"
        working-directory: build
      - run: make -j
        working-directory: build
      - run: make -j check
        working-directory: build
        env:
          ASAN_OPTIONS: detect_leaks=1
          UBSAN_OPTIONS: print_stacktrace=1:halt_on_error=1
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: sanitizers-${{ matrix.sanitizer }}-${{ matrix.threadsafe && 'ts' || 'nots' }}
          path: |
            build/**/*.log
            build/config.log

  distcheck:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Distcheck ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update; sudo apt install -y gcc ruby-dev libgsl-dev python3-dev
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - run: brew install gsl automake libtool
        if: ${{ matrix.os == 'macos-latest' }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        if: ${{ matrix.os == 'macos-latest' }}
      - run: gem install --user-install rake ffi ffi-value whittle xmlrpc
      - run: pip3 install --user parglare
      - run: ./autogen.sh
      - run: mkdir -p build
      - run: ../configure --enable-strict
        working-directory: build
      - run: make -j distcheck
        working-directory: build

  coverage:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Code Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update; sudo apt install -y gcc ruby-dev libgsl-dev python3-dev lcov
      - run: gem install --user-install rake ffi ffi-value whittle xmlrpc
      - run: pip3 install --user parglare
      - run: ./autogen.sh
      - run: mkdir -p build
      - run: ../configure --enable-code-coverage --enable-thread-safe CFLAGS="-O0 -g -fprofile-arcs -ftest-coverage -fprofile-update=atomic"
        working-directory: build
      - run: make -j
        working-directory: build
      - run: make -j check-code-coverage
        working-directory: build
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: build/cconfigspace-*-coverage/

  dist-check:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Dist and Check ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update; sudo apt install -y gcc ruby-dev libgsl-dev python3-dev
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - run: brew install gsl automake libtool
        if: ${{ matrix.os == 'macos-latest' }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        if: ${{ matrix.os == 'macos-latest' }}
      - run: gem install --user-install rake ffi ffi-value whittle xmlrpc
      - run: pip3 install --user parglare
      - run: ./autogen.sh
      - run: mkdir -p build
      - run: ../configure --enable-strict
        working-directory: build
      - run: make dist
        working-directory: build
      - name: extract
        run: tar -xzvf cconfigspace-*
        working-directory: build
      - name: configure
        run: |
          cd `find . -type d -name "cconfigspace-*"`
          mkdir -p build
          cd build
          ../configure
        working-directory: build
      - name: make check
        run: |
          cd `find . -type d -name "cconfigspace-*"`
          cd build
          make -j check
        working-directory: build
